directories:
  articles: /apps/nets-pipeline-home/data
  persist: /tmp/

pipeline:
  delay: 4
  batchsize: 2
  components:
  - nlp
  - geocode
  - persisttofile
  

elasticsearch:
  host: localhost
  port: 9200
  indexes:
  - type: raw-article
    name: nets-raw-article
    doctype: nets-article
  - type: enhanced-article
    name: nets-enhanced-document
    doctype: enhanced-document

opensextant:
  base: http://localhost:8182/opensextant

logging:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

