directories:
  articles: /apps/nets-pipeline-home/data
  persist: /Users/haley/Projects/RadiantBlue/nets/nets-documents/

pipeline:
  delay: 4
  batchsize: 2
  components:
  - nlp
  - clavin-geocode
  - nominatim-geocode
  - mapzen-geocode
  - ost-geoparse
  - clavin-geoparse
  - persisttofile
  

elasticsearch:
  host: localhost
  port: 9200
  indexes:
  - type: raw-article
    name: nets-raw-article
    doctype: nets-article
  - type: enhanced-article
    name: nets-enhanced-document
    doctype: enhanced-document

opensextant:
  geoparse: http://localhost:8182/opensextant/extract/geo/json

clavin:
  geocode: https://lew.geointservices.io/v1/geo/getLocationsExpanded
  geoparse: http://localhost:9090/api/v0/geotag
  
nominatim:
  geocode: http://nominatim.openstreetmap.org/search

mapzen:
  geocode: https://search.mapzen.com/v1/search

logging:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

